name: Broken Link Checker
on:
  repository_dispatch:
    types: [test]
  workflow_dispatch:
  schedule:
    - cron: '00 18 * * *'
jobs:
  linkChecker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Check Links
        id: lychee
        uses: lycheeverse/lychee-action@v1.10.0
        with:
          args: --verbose --no-progress './**/*.md' './**/*.html' './**/*.json' --exclude-mail --exclude 'http://localhost:*/*' --exclude 'https://*.canva.com/*' --exclude 'https://*.udemy.com/*' --exclude 'https://*.leetcode.com/*' --exclude 'https://*.codeforces.com/*' --exclude 'https://*.pexels.com/*' --exclude 'https://*.pixabay.com/*'
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
        continue-on-error: true

      - name: Set lychee_exit_code
        id: lychee_exit_code
        run: echo "::set-output name=lychee_exit_code::$?"

      - name: Commit changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git commit -m "Fix broken links" -a || echo "No changes to commit"
        shell: bash

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: 'Fix broken links'
          title: 'Fix broken links'
          body: 'This PR fixes broken links found by the link checker.'
          branch: 'fix/broken-links'

      - name: Create Issue From File
        if: steps.lychee_exit_code.outputs.lychee_exit_code != 0
        uses: peter-evans/create-issue-from-file@v5.0.0
        with:
          title: Link Checker Report
          content-filepath: ./lychee/out.md
          labels: Broken Link
